version: "3.9"
services:
  web:
    build: .
    image: ${CONTAINER_NAME}
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
